
#' @title LoadModel: loading a trained MOFA model from python output
#' @name loadModel
#' @description Method to load a trained MOFA model from a hdf5 file. \cr
#' Models have to be trained and saved using the corresponding Python package.
#' @param file an hd5f model generated by the MOFA python package.
#' @details fill this
#' @return a \code{\link{MOFAmodel}} model.
#' @import rhdf5
#' @export

loadModel <- function(file, model=NULL) {
  
  if(is.null(model)) model <- new("MOFAmodel")
  
  if(.hasSlot(model,"Status") & length(model@Status) !=0)
    if (model@Status == "trained") warning("The specified model is already trained, over-writing training output with new results!")
  
  # Load expectations and parameters
  model@Expectations <- rhdf5::h5read(file,"expectations")
  model@Parameters <- rhdf5::h5read(file,"parameters")
  model@Status <- "trained"
  
  # Load training statistics
  tryCatch( {
    model@TrainStats <- rhdf5::h5read(file, 'training_stats',read.attributes=T);
    colnames(model@TrainStats$elbo_terms) <- attr(rhdf5::h5read(file,"training_stats/elbo_terms", read.attributes=T),"colnames")
  }, error = function(x) { print("Training stats not found, not loading it...") })

  
  # Load training options
  if(.hasSlot(model,"TrainOpts") & length(model@TrainOpts) == 0){
    if(!all(model@TrainOpts == as.list(rhdf5::h5read(file, 'training_opts',read.attributes=T)))) 
      warning("TrainOpts already defined in the model but not in agreement with trained model, over-writting pre-defined TrainOpts")
  }
  tryCatch(model@TrainOpts <- as.list(rhdf5::h5read(file, 'training_opts',read.attributes=T)), error = function(x) { print("Training opts not found, not loading it...") })
  
  # Load model options
  if(.hasSlot(model,"ModelOpts") & length(model@ModelOpts) == 0){
    if(!all(model@ModelOpts == as.list(rhdf5::h5read(file, 'model_opts',read.attributes=T)))) 
      warning("ModelOpts already defined in the model but not in agreement with trained model, over-writting pre-defined ModelOpts")
  }
  tryCatch(model@ModelOpts <- as.list(rhdf5::h5read(file, 'model_opts',read.attributes=T)), error = function(x) { print("Model opts not found, not loading it...") })
  
  # Load training data


  tryCatch( {
    TrainingData <- rhdf5::h5read(file,"data")
    featuredata <- rhdf5::h5read(file,"features")
    sampledata <- rhdf5::h5read(file,"samples")
    for (m in names(TrainingData)) {
      rownames(TrainingData[[m]]) <- sampledata
      colnames(TrainingData[[m]]) <- featuredata[[m]]
    }
    TrainingData <- lapply(TrainingData, t)
    if(.hasSlot(model,"TrainData") & length(model@TrainData) != 0){
      if(!identical(TrainingData, model@TrainData)) 
        warning("TrainData already defined in the model but not in agreement with trained model, over-writting pre-defined TrainData and Dimensions")
    }
    model@TrainData <- TrainingData
    model@Dimensions[["M"]] <- length(model@TrainData)
    model@Dimensions[["N"]] <- ncol(model@TrainData[[1]])
    model@Dimensions[["D"]] <- sapply(model@TrainData,nrow)
    model@Dimensions[["K"]] <- ncol(model@Expectations$Z$E)
    viewNames(model) <- names(model@TrainData)
    sampleNames(model) <- colnames(model@TrainData[[1]])
    featureNames(model) <- lapply(model@TrainData,rownames)
    factorNames(model) <- as.character(1:model@Dimensions[["K"]])
    # K=tail(training_stats$activeK[!is.nan(training_stats$activeK)],n=1)
    }, error = function(x) { print("Error loading the data...") })
  
  return(model)
}

