
############################################
## Functions to load a trained MOFA model ##
############################################


#' @title loadModel: loading a trained MOFA model from python output
#' @name loadModel
#' @description Method to load a trained MOFA model from a hdf5 file. \cr
#' Models have to be trained and saved using the corresponding Python package.
#' @param file an hd5f model generated by the MOFA python package.
#' @details fill this
#' @return a \code{\link{MOFAmodel}} model.
#' @importFrom rhdf5 h5read
#' @export

loadModel <- function(file, object=NULL, sortFactors=T) {
  
  message(paste0("Loading the following MOFA model: ", file))
  
  if (is.null(object)) object <- new("MOFAmodel")
  
  # if(.hasSlot(object,"Status") & length(object@Status) !=0)
  #   if (object@Status == "trained") warning("The specified object is already trained, over-writing training output with new results!")
  
  # Load expectations and parameters
  object@Expectations <- h5read(file,"expectations")
  object@Parameters <- h5read(file,"parameters")
  object@Status <- "trained"
  
  # Load training statistics
  tryCatch( {
    object@TrainStats <- h5read(file, 'training_stats',read.attributes=T);
    colnames(object@TrainStats$elbo_terms) <- attr(h5read(file,"training_stats/elbo_terms", read.attributes=T),"colnames")
  }, error = function(x) { print("Training stats not found, not loading it...") })

  
  # Load training options
  if (length(object@TrainOpts) == 0) {
    tryCatch(object@TrainOpts <- as.list(h5read(file, 'training_opts',read.attributes=T)), error = function(x) { print("Training opts not found, not loading it...") })
  }
    
  # Load model options
  if (length(object@ModelOpts) == 0) {
    tryCatch(object@ModelOpts <- as.list(h5read(file, 'model_opts',read.attributes=T)), error = function(x) { print("Model opts not found, not loading it...") })
  }
  
  # Load training data
  if (length(object@TrainData) == 0) {
  tryCatch( {
    TrainData <- h5read(file,"data")
    featureData <- h5read(file,"features")
    sampleData <- h5read(file,"samples")
    for (m in names(TrainData)) {
      rownames(TrainData[[m]]) <- sampleData
      colnames(TrainData[[m]]) <- featureData[[m]]
    }
    TrainData <- lapply(TrainData, t)
    object@TrainData <- TrainData
    }, error = function(x) { print("Error loading the training data...") })
  }
  
  # Load dimensions and names
  object@Dimensions[["M"]] <- length(object@TrainData)
  object@Dimensions[["N"]] <- ncol(object@TrainData[[1]])
  object@Dimensions[["D"]] <- sapply(object@TrainData,nrow)
  # K=tail(training_stats$activeK[!is.nan(training_stats$activeK)],n=1)
  object@Dimensions[["K"]] <- ncol(object@Expectations$Z$E)
  viewNames(object) <- names(object@TrainData)
  sampleNames(object) <- colnames(object@TrainData[[1]])
  featureNames(object) <- lapply(object@TrainData,rownames)
  factorNames(object) <- as.character(1:object@Dimensions[["K"]])
    
  # Rename covariates
  if (object@ModelOpts$learnMean == TRUE) factorNames(object) <- c("intercept",as.character(1:(object@Dimensions[["K"]]-1)))
  if (!is.null(object@ModelOpts$covariates)) {
    if (object@ModelOpts$learnMean == TRUE) {
      factorNames(object) <- c("intercept", colnames(object@ModelOpts$covariates), as.character((ncol(object@ModelOpts$covariates)+1:(object@Dimensions[["K"]]-1-ncol(object@ModelOpts$covariates)))))
    } else {
      factorNames(object) <- c(colnames(object@ModelOpts$covariates), as.character((ncol(object@ModelOpts$covariates)+1:(object@Dimensions[["K"]]-1))))
    }
  }
  
  if (sortFactors) {
    stop()
    # Re-name and order factors in order of variance explained and label intercept
    r2 <- rowSums(calculateVarianceExplained(object,plotit=F)$R2PerFactor)
    order_factors <- c("intercept",names(r2)[order(r2, decreasing = T)])
    object <- subsetFactors(object,order_factors)
    # factorNames(object) <- 
  }
  return(object)
}

